### ISSUE TITLE
Electron 2.0? Doesn't seem to work.

### ISSUE THREAD

**Issue by Nantris** [Teamwork/node-auto-launch#84]
The path option in Electron 2.0.x seems to return: `TypeError: Path must be a string. Received undefined`

**Comment by Slapbox** [comment]
Specifically this error is coming from the `isEnabled` function on Windows. I have tried everything under the sun today to get this working... Any ideas would be greatly appreciated.

**Comment by Slapbox** [comment]
```
[16:27:29.911] TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:501:7)
    at g (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:346:321590)
    at v.set (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:346:325593)
    at e.exports.enable (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:346:328314)
    at new Promise (<anonymous>)
    at Object.enable (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:346:328008)
    at e.exports.e.enable (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:346:329793)
    at e.i [as enable] (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:346:328775)
    at setAutoLaunch (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:346:331162)
    at t.value (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:451:246586)
    at lo (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:459:55778)
    at Do (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:459:65094)
    at fa (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:459:77144)
    at ha (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:459:77452)
    at Xa (file:///C:/Users/user/AppData/Local/Programs/myApp/resources/app.asar/dist/renderer.prod.js:459:81001)
```

**Comment by Slapbox** [comment]
This might be due to this issue with the Node path module. https://github.com/nodejs/node/issues/21392

**Comment by Oxalin** [comment]
Closing. If this is still an issue with latest code and electron, let us know.
